server:
  port: 4446

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5433/postgres
#    username: postgres
#    password: pass
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: false
        jdbc:
          timezone: UTC